### ISSUE TITLE
api.name

### ISSUE THREAD

**Issue by nobountyhunter** [Cappi1998/SteamAccountCreateHelper#5]
Hello Cappi, api.namefake.com is it working? I can't create a named login, can you give a configuration for random names?

**Comment by Cappi1998** [comment]
Hii, I just tested and the api.namefake.com api is working correctly.

you can configure a "custom Format" if you wish

for example: {singlenum}_fabiocapp{letter}_{num}{letter}

will generate logins like these:

1_fabiocappd_264238755g
3_fabiocappk_39058620f
6_fabiocappy_30633434x
5_fabiocapph_220133827i

![image](https://user-images.githubusercontent.com/26587371/165185685-87cc3bf7-80c1-48bc-8c77-da6ec890005c.png)
